<?php 
$broadcast_config=array(
'facebook_profile'=>"1",
'facebook_page'=>"1",
'facebook_page_limit'=>"10",
'facebook_profile_limit'=>"10",
'twitter'=>"1",
'twitter_limit'=>"10",
'linkedin'=>"1",
'linkedin_limit'=>"10",
'private_key_cronjob'=>"1234",
'url_limit'=>"10",
'rss_link_limit'=>"3",
'status_via'=>"0",
'status_skip'=>"#,@"
);
?>